### ISSUE TITLE
Any plans to 0.0.4?

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/rules_jsonnet#108]
Last release, 0.0.3, is 2 years old. It no longer works with current version of bazel. Sample code on readme points to it and makes adoption harder. A new release and documentation would be really nice.

**Comment by Globegitter** [comment]
Yeah fair point, will make a release and updates in the coming days.

**Comment by Globegitter** [comment]
Released as 0.1.0.

**Comment by Globegitter** [comment]
While you are  totally right about adoption and first-use experience I can also recommend the tool https://github.com/bzl-io/bzl to make updates of bazel deps easier.
