### ISSUE TITLE
jsonnet -S/--string feature missing

### ISSUE THREAD

**Issue by 5h4d0w4rt** [bazelbuild/rules_jsonnet#115]
Hello!
It seems that current rules does not support jsonnet -S

> -S / --string           Expect a string, manifest as plain text

I'm new to starlark and this repo, could you please point me out to what exactly should i do to contribute this feature as PR?

**Comment by Globegitter** [comment]
Yep of course, any contributions are very much appreciated. First of all I would recommend the bazel documentation and https://github.com/bazelbuild/examples to get some basic understanding about the wiritng of rules. Then specifically for these rules you would have to add an additional attribute in this dict: https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L475 and then make sure it is being passed through to jsonnet here: https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L195 and here: https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L350

Please also write a test that makes use of this new flag/attribute.

**Comment by 5h4d0w4rt** [comment]
> 
> 
> Yep of course, any contributions are very much appreciated. First of all I would recommend the bazel documentation and https://github.com/bazelbuild/examples to get some basic understanding about the wiritng of rules. Then specifically for these rules you would have to add an additional attribute in this dict: https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L475 and then make sure it is being passed through to jsonnet here: https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L195 and here: https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L350
> 
> Please also write a test that makes use of this new flag/attribute.

Gotcha, thanks. Will do.

**Comment by EdSchouten** [comment]
It turns out that it is nowadays possible to emit raw strings by using:
```python
extra_args = ["--string"]
```
This has been documented as part of #186. Closing this issue. Thanks for reporting it!
