### ISSUE TITLE
update rules to jsonnet interpreter v0.14

### ISSUE THREAD

**Issue by 5h4d0w4rt** [bazelbuild/rules_jsonnet#116]
Hello!
Jsonnet v0.14 is out for pretty long time and i think we should update? 
Current rules release still use v0.13.

**Comment by Globegitter** [comment]
Yep that would be great, are you up for sending a PR for that @5h4d0w4rt ?

**Comment by 5h4d0w4rt** [comment]
> 
> 
> Yep that would be great, are you up for sending a PR for that @5h4d0w4rt ?

Definitely! Might take a while but i'm on it. :)
