### ISSUE TITLE
Please do a new release to support Bazel 5

### ISSUE THREAD

**Issue by tjoneslo** [bazelbuild/rules_jsonnet#149]
Due to issue #147 the current release of `rules_jsonnet` is not compatible with the Bazel 5.0.0 release. There is an incompatibility flag that would allow these rules to work, but it seems to be broken in the rc2 release (issue has been filed)

So a new release would be wonderful to make sure our transition to Bazel 5 is as smooth as possible. 

Thank you for your time.

**Comment by illicitonion** [comment]
Hi @sparkprime 👋! Any chance I could nudge you towards pushing a release? Smoothing the on-ramp to the Bazel 5 release would be lovely :) Cheers!

**Comment by sparkprime** [comment]
Does this repo even have releases?  Not sure what to do.

**Comment by sparkprime** [comment]
I have remembered how to use Github, and given the release a very unimaginative name :+1:

**Comment by illicitonion** [comment]
Beautiful, thank you so much! 🎉 🙏 

Long live 0.4.0!

**Comment by anguslees** [comment]
I think we can close this issue now?
