### ISSUE TITLE
Update to jsonnet 0.9.0

### ISSUE THREAD

**Issue by gsf** [bazelbuild/rules_jsonnet#15]
Any plans to update to jsonnet 0.9.0?

**Comment by sparkprime** [comment]
I guess this means adding support for top-level arguments?

**Comment by gsf** [comment]
A release supporting 0.8.9 might also be a useful target.

**Comment by macrael** [comment]
0.8.8 crashes attempting to import ksonnet, it would be nice if it were updated without any api change just to allow for new syntax in jsonnet files.

**Comment by guoshimin** [comment]
The issue has been open for a year now. Can we upgrade jsonnet to the latest version (v0.9.5)?
