### ISSUE TITLE
incorrect version linked?

### ISSUE THREAD

**Issue by HaberR** [bazelbuild/rules_jsonnet#156]
This text is in the README for version 0.4.0:

```
http_archive(
    name = "io_bazel_rules_jsonnet",
    sha256 = "7f51f859035cd98bcf4f70dedaeaca47fe9fbae6b199882c516d67df416505da",
    strip_prefix = "rules_jsonnet-0.3.0",
    urls = ["https://github.com/bazelbuild/rules_jsonnet/archive/0.3.0.tar.gz"],
)
load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_repositories")

jsonnet_repositories()

load("@google_jsonnet_go//bazel:repositories.bzl", "jsonnet_go_repositories")

jsonnet_go_repositories()

load("@google_jsonnet_go//bazel:deps.bzl", "jsonnet_go_dependencies")

jsonnet_go_dependencies()
```

I think all the '3's in the http_archive need to be switched to '4's, and probably the sha256 needs updating too? Unfortunately, because the method for loading the repositories/dependencies has changed between versions, none of it will work as written in the README, I don't think.

Looking forward to using top level arguments!

**Comment by EdSchouten** [comment]
This should be fixed in #179. The instructions in the README.md now state how to use rules_jsonnet 0.5.0 from bzlmod or as part of WORKSPACE.
