### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break rules_jsonnet in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/rules_jsonnet#166]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking rules_jsonnet. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS, OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-ee1b-40bf-976b-8ed2dca3406e)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-ee18-4a11-820f-eda50b735fe8)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi Team, Gentle ping , Can you share any significant update on this issue. Thanks!

**Comment by sparkprime** [comment]
I changed 2 "host" that i found to "exec"
