### ISSUE TITLE
no such package '@@bazel_tools//platforms' in bazel build 

### ISSUE THREAD

**Issue by simonff** [bazelbuild/rules_jsonnet#196]
Hi! I'm trying to follow the process we recommend to the [external users of our repo](https://github.com/google/earthengine-catalog/blob/main/docs/install.md), but I'm running into problems.

If I git clone [https://github.com/google/earthengine-catalog](https://github.com/google/earthengine-catalog%60), remove .bazelversion that pins bazel to an old version, and then run bazel build --define jsonnet_port=cpp //... in the top directory, I get:

ERROR: no such package '@@bazel_tools//platforms': BUILD file not found in directory 'platforms' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package.

This is probably due to the jsonnet_to_json rule [that we load here](https://github.com/google/earthengine-catalog/blob/main/BUILD#L5), but I don't understand enough how bazel+jsonnet work together to ask a more intelligent question.

**Comment by EdSchouten** [comment]
I see that in addition to the old version of Bazel that this repo uses, it is also using an old version of rules_jsonnet:

https://github.com/google/earthengine-catalog/blob/main/WORKSPACE#L5-L10

My recommendation would be to remove the WORKSPACE file entirely, and write a new MODULE.bazel file that depends on the latest version of rules_jsonnet that's in BCR:

https://registry.bazel.build/modules/rules_jsonnet

**Comment by simonff** [comment]
Thank you very much, this helped . Now I know the new way.
