### ISSUE TITLE
How do you import an external jsonnet library?

### ISSUE THREAD

**Issue by macrael** [bazelbuild/rules_jsonnet#25]
I'm trying to import ksonnet into a jsonnet file using bazel and I'm not sure how to do that. 

Right now I've got the following:

WORKSPACE
```
# KSonnet
ksonnet_build_file = '''
filegroup(
    name = "ksonnet_files",
    srcs = glob(["ksonnet.beta.2/*.libsonnet"]),
    visibility = ["//visibility:public"],
)
'''

new_git_repository(
    name = "com_github_ksonnet_lib",
    remote = "https://github.com/ksonnet/ksonnet-lib.git",
    tag = "beta.2",
    build_file_content = ksonnet_build_file,
)
```
BUILD
```
jsonnet_library(
    name = "ksonnet-lib",
    srcs = [
        "@com_github_ksonnet_lib//:ksonnet_files",
    ],
)

jsonnet_to_json(
    name = "transform-receiver-test",
    src = "receiver.jsonnet",
    outs = ["receiver-test.json"],
    deps = ["ksonnet-lib"]
)
```
receiver.jsonnet
```
local k = import "external/com_github_ksonnet_lib/ksonnet.beta.2/k.libsonnet";
```

The import statement is not working. It's not clear to me what ksonnet-lib is supposed to do with the input files it's given. Does it create a new importable file? 

Actually, this is almost working. Is jsonnet_library equivalent to a filegroup? Should I be adding an import call to the jsonnet_to_json call?

**Comment by macrael** [comment]
So, the above actually works. I'm getting an error because the version of jsonnet y'all install is out of date. 

I'm not super pleased with the lengthy import statement required here, it'd be nice if jsonnet_library created an importable file, I think.

**Comment by sparkprime** [comment]
I think you can add import = "external/com_github_ksonnet_lib" to your jsonnet_library rule (or something like that).  Then you would import "ksonnet.beta.2/k.libsonnet".  (Or even hide the version dir if you wanted).

The version will be updated to 0.10.0 presently.
