### ISSUE TITLE
Rules Jsonnet somehow conflict with cloud.google.com/go

### ISSUE THREAD

**Issue by macrael** [bazelbuild/rules_jsonnet#27]
I get the following error when trying to run a bazel rule that depends on the google cloud go api if my workspace also loads jsonnet_repositories.  

```
ERROR: .../external/com_github_googleapis_gax_go/BUILD.bazel:5:1: no such package '@org_golang_google_grpc//status': BUILD file not found on package path and referenced by '@com_github_googleapis_gax_go//:go_default_library'.
ERROR: Analysis of target '//deploy:deploy-to-minikube' failed; build aborted.
```

I am very puzzled by this, I don't see why jsonnet_repositories could trample an unrelated package.

**Comment by Globegitter** [comment]
@macrael I will close this, but if this is still an issue please open another issue with a reproduction repository.
