### ISSUE TITLE
This needs examples that work with K8s objects

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_jsonnet#28]
It could probably also use rules to make consuming [this](https://github.com/ksonnet/ksonnet-lib) straightforward.

**Comment by mattmoor** [comment]
@damienmg Who owns this repo?

**Comment by damienmg** [comment]
@davidzchen

**Comment by mattmoor** [comment]
@mmikulicic It seems like what you have in https://github.com/mmikulicic/rules_ksonnet would be a great extension to this repo (and foundation for this bug).  Any interest in reconciling these two repos via a PR?

My goal is to add samples to `rules_k8s` that use `jsonnet` templating, fed into a `k8s_object` rules for some of its capabilities around image integration and various action commands.

WDYT?

**Comment by mmikulicic** [comment]
> Any interest in reconciling these two repos via a PR?
yeah sure. I have no good idea about how to proceed though.

**Comment by mattmoor** [comment]
@mmikulicic For this logic [here](https://github.com/mmikulicic/rules_ksonnet/blob/master/ksonnet.bzl#L20-L30)

I'm wondering it it is feasible to make `ksonnet-lib` available as a `jsonnet_library` to these rules, and achieve what it does via `jsonnet_to_json`?

**Comment by mattmoor** [comment]
To be clear, I'm not 100% clear on what functionality of `kubecfg` you are relying on vs. pure `jsonnet`, so call me crazy if this is crazy :)

**Comment by mmikulicic** [comment]
IIRC that part was pure jsonnet. I planned to also have kubecfg handy to do updates and diffs, but this can be done after the evaluation step is done

**Comment by mattmoor** [comment]
@mmikulicic I think those are both generally useful independent of `jsonnet`, and `rules_k8s` already supports `kubectl replace`.

What I had in mind was:
```python
jsonnet_to_json(
    name = "foo",
    srcs = [...]
    out = "foo.json",
    deps = [...]
)

k8s_object(
    name = "bar",
    template = ":foo.json",
    images = { ... },
)
```

You can then run: `bazel run :bar.replace` for replacement today, but I think `bazel run :bar.diff` sounds interesting too.

Does this seem like a reasonable goal to you?  What might you change?

**Comment by anzdaddy** [comment]
These projects are clearly complementary, but I'm not sure that justifies merging them into a single repo. Perhaps there's an argument to be made for refactoring rules_ksonnet to leverage rules_jsonnet, but I don't see much benefit in mashing the two into one.

**Comment by mattmoor** [comment]
I think the pertinent question is whether we should even have `ksonnet` **rules**, or just strong examples of how to use `ksonnet-lib` with `rules_jsonnet`.

I definitely think we could encapsulate the example flow in macros in `rules_ksonnet`, but I'm wondering how much it would really save.

**Comment by sparkprime** [comment]
Let's keep k8s rules & examples out of this repo, but obviously using this repo in tools that marry k8s with Jsonnet makes sense.
