### ISSUE TITLE
Support stamp variables

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_jsonnet#29]
Not sure what facilities exist at the `jsonnet` level for injecting this kind of thing, but especially in the context of Kubernetes templating it would be fantastic if we could optionally inject build context.

The particular scenario I am envisioning would be environment modeling, where I might want to inject `{BUILD_USER}` into the template expansion (e.g. as a Docker Image tag).  Or for integration testing on PRs I might want an environment per PR based on the PR number, which might come through `--workspace_status_command`.

**Comment by justinwp** [comment]
My use case is getting the git branch and hash into labels for rules_k8s.

**Comment by ashi009** [comment]
The best I can think of is to use `--ext-code buildstamp={...}` to pass in such info, and create a libsonnet package to consume it with `{default: 'stamping', info: 'is herer'} + std.extVar('buildstamp')`.

The problem with this approach is that, whenever `--ext-code` flag is not presented, the build will fail. Which will probably break all dev tool integrations.

**Comment by ashi009** [comment]
Ah, another option is to create a generated `jsonnet_library` which contains all the stamping variables. When build in bazel use this generated library, and for dev tools, use the actual file in the search path.

**Comment by mattmoor** [comment]
@ashi009 I can introduce new stamping variables through `--workspace_status_command`, so for this to be exhaustive we must **dynamically generate** the `.jsonnet` for your library based on these files, which would be kinda bad ass. :)

**Comment by mattmoor** [comment]
rereading your answer, it already says "generate", so sorry for not RTFM.  That's be great, I think.

**Comment by ashi009** [comment]
@mattmoor I've tried to create such `libsonnet` package with stamp variables inside, then it turned out that `rules_jsonnet` doesn't know how to handle generated files.  Additional `-J` flags need to be passed to `jsonnet`.

**Comment by mattmoor** [comment]
Awesome!  Would you be able to turn that into a PR?

**Comment by ashi009** [comment]
One thing I don't like my CL is that, `-J .` is not generated from `search_paths`, but instead manually pinned to appear before all other `-J` flags.  The reason for doing this is because the generated file shared the same name as the placeholder file. So unless `-J .` appears before the rest, the placeholder file will be used.   Which doesn't seem right to me as the placeholder file is not on the transitive dependency graph. 🤦‍♂️

**Comment by sparkprime** [comment]
I just merged something (hadn't seen this) that might help with this: https://github.com/bazelbuild/rules_jsonnet/pull/37/files

**Comment by mariusgrigoriu** [comment]
What about expanding make variables with defined with `--define`?

**Comment by mariusgrigoriu** [comment]
I created a separate issue #39 (and matching PR) since stamp variables would be useful anyway.
