### ISSUE TITLE
Multiple outputs without knowing the filenames beforehand

### ISSUE THREAD

**Issue by glindste** [bazelbuild/rules_jsonnet#33]
Would it be possible to get multiple file outputs without having to list them in the `outs` of the `jsonnet_to_json` rule? Currently I have files with dynamically generated filenames for the outputs, similar to this:
```
{
    [name + "-file.json"]: someStructure(),
}
```
Though it would be possible it becomes quite a hassle to have to declare _every_ generated file once complexity increases, if using this pattern.

I'm not that familiar with bazel so I don't know if this is possible, or if it requires static knowledge of the output files.

**Comment by sparkprime** [comment]
I don't think it's possible because bazel needs to statically understand the dependency tree.  @davidzchen can correct me

**Comment by sparkprime** [comment]
I'm going to close this unless someone can tell me that this mode of operation is something Bazel is designed to support.
