### ISSUE TITLE
Generated src don't import correctly

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_jsonnet#44]
If you add the following to examples/BUILD:
```
genrule(
    name = "generated",
    outs = ["generated.jsonnet"],
    cmd = "echo \"(import 'import_me.libsonnet')\" > $@"
)

jsonnet_to_json(
    name = "import",
    src = "generated.jsonnet",
    imports = ["examples"],
    deps = [":import_lib"],
    outs = ["import.json"],
)

jsonnet_library(
    name = "import_lib",
    srcs = ["import_me.libsonnet"],
)
```

Results in an error:
```
RUNTIME ERROR: Couldn't open import "import_me.libsonnet": No match locally or in the Jsonnet library paths.
```

The command emitted by the rule is `/bin/bash -c 'set -e; bazel-out/host/bin/external/jsonnet/cmd/jsonnet -J . -J bazel-out/darwin-fastbuild/genfiles -J bazel-out/darwin-fastbuild/bin bazel-out/darwin-fastbuild/genfiles/external/examples/generated.jsonnet -o bazel-out/darwin-fastbuild/bin/external/examples/import.json'`

However, if src = some identical file that lives in the examples directory along with the import_me.libsonnet, then everything works.

In my real-world project I am able to workaround by adding `imports = ["."],` but that does not work in the examples directory, maybe because it is a workspace root and `-J /. ` is appended to the command. Not sure how to make the scenario pass in the examples.

Is this expected behavior?

**Comment by EdSchouten** [comment]
This should be fixed in #182. We now properly respect `ctx.file.srcs[].root.path` when constructing import paths. These rules should therefore no longer have any problems importing generated source files. Thanks for reporting this issue!
