### ISSUE TITLE
Unable to use ext_strs with literal key-value pairs

### ISSUE THREAD

**Issue by atavakoli** [bazelbuild/rules_jsonnet#49]
Based on the documentation, I expect to be able to pass in literal key-value pairs in the `ext_strs` dict:

> Map of strings to pass to jsonnet as external variables via `--ext-str key=value`.

and not names of configuration variables.

However, at [jsonnet.bzl, line 118](https://github.com/bazelbuild/rules_jsonnet/blob/6dd47d83adda2dc7fce24a7b45dee202d7575625/jsonnet/jsonnet.bzl#L118), the value of the external string is taken using `_quote(ctx.var[val])`. Is there a reason `_quote(val)` was not used instead?

**Comment by Globegitter** [comment]
Yeah the latest commit https://github.com/bazelbuild/rules_jsonnet/commit/6dd47d83adda2dc7fce24a7b45dee202d7575625 broke that. You can just depend on the commit before that. My pr #52 should also fix that.
