### ISSUE TITLE
"jsonnet_to_json" "outs" attribute does not allow writing to multiple directories

### ISSUE THREAD

**Issue by seh** [bazelbuild/rules_jsonnet#56]
The _jsonnet_ command-line tool can emit JSON to multiple files when invoked with the `-m` flag. It interprets the keys of the top-level map as file paths to which to write. Those paths can include not just a file name, but a directory path as well. Though the _jsonnet_ tool does not create these output directories, if you first ensure that they do exist, it will write the output files to the proper directories. That is, when facing manifested JSON with the following top level structure
```json
{
  "dir1/file1.json": {},
  "dir2/file2.json": {}
}
```
the _jsonnet -m parent_ command will write to
- _parent/dir1/file1.json_
- _parent/dir2/file2.json_

as intended.

However, the `jsonnet_to_json` rule precludes this behavior. Instead, [it infers the value of `-m` flag to be the directory path of the first output file](https://github.com/bazelbuild/rules_jsonnet/blob/master/jsonnet/jsonnet.bzl#L138). In the example above, `jsonnet_to_json` sees that the first output path has _dir1_ as its directory, and decides to pass `-m dir1` to _jsonnet_, causing it to try to write to the following paths:
- _dir1/dir1/file1.json_
- _dir1/dir2/file2.json_

Even if we had taken care to create _dir1_ and _dir2_ beforehand, _jsonnet_ will still fail to write those files, as neither directory _dir1/dir1_ nor _dir1/dir2_ are likely to exist.

Better would be to accept an optional attribute to designate the root output directory, with a default value of '.' (the current directory), and not make any assumptions about the first output path being indicative of the others.

**Comment by seh** [comment]
I see that @davidzchen introduced this behavior in commit 03d36d12c43d8d45415d9144881c0b67ae6daca5.

**Comment by EdSchouten** [comment]
I've just added some code to compute the leading part of the directory name that is shared by all output files. That should be a decent enough heuristic.
