### ISSUE TITLE
Library with data in a nested workspace

### ISSUE THREAD

**Issue by mtsgrd** [bazelbuild/rules_jsonnet#86]
I have a `jsonnet_library` in an external workspace that uses `importstr` to load a text file included in the data attribute. This only works if I add an `external/...` prefix to the import paths, which then doesn't work when developing that imported project separately. Does anyone have any idea of how to solve this?

**Comment by EdSchouten** [comment]
With #182 landed, this should work out of the box. There no longer is any need to provide the `external/*` prefix. Whether a module is a root or not is now irrelevant.
